<?php

namespace BackendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * YellowCardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YellowCardRepository extends EntityRepository
{
   /**
    * Finds all entities in the repository.
    *
    * @return array The entities.
    */

      public function findAllCards()
      {
          return $this->findBy(array(), array('id' => 'DESC'));
      }
}
